# SPDX-License-Identifier: AGPL-3.0-or-later
# mwStime — Akai S-series timestretch emulation. Copyright (C) 2026 mattWoolly.
#
# CTest helper (run via `cmake -P`): regenerate the golden input corpus into a
# scratch dir with gen_golden_inputs, then assert every committed WAV under
# COMMITTED_DIR is byte-identical to the freshly generated one. Proves the inputs
# are reproducible from the committed generator (task 026 acceptance criterion).
#
# Required -D vars: GEN_BIN, COMMITTED_DIR, SCRATCH_DIR.

if(NOT DEFINED GEN_BIN OR NOT DEFINED COMMITTED_DIR OR NOT DEFINED SCRATCH_DIR)
    message(FATAL_ERROR "CheckInputsReproducible: GEN_BIN/COMMITTED_DIR/SCRATCH_DIR required")
endif()

file(REMOVE_RECURSE "${SCRATCH_DIR}")
file(MAKE_DIRECTORY "${SCRATCH_DIR}")

execute_process(
    COMMAND "${GEN_BIN}" "${SCRATCH_DIR}"
    RESULT_VARIABLE gen_rc
    OUTPUT_VARIABLE gen_out
    ERROR_VARIABLE gen_err
)
if(NOT gen_rc EQUAL 0)
    message(FATAL_ERROR "gen_golden_inputs failed (rc=${gen_rc}):\n${gen_out}\n${gen_err}")
endif()

# Every committed input WAV must have a byte-identical regenerated twin.
file(GLOB committed_wavs "${COMMITTED_DIR}/*.wav")
if(committed_wavs STREQUAL "")
    message(FATAL_ERROR "no committed inputs found in ${COMMITTED_DIR}")
endif()

set(mismatches "")
foreach(wav ${committed_wavs})
    get_filename_component(name "${wav}" NAME)
    set(regen "${SCRATCH_DIR}/${name}")
    if(NOT EXISTS "${regen}")
        list(APPEND mismatches "${name} (generator did not produce it)")
        continue()
    endif()
    file(SHA256 "${wav}" committed_hash)
    file(SHA256 "${regen}" regen_hash)
    if(NOT committed_hash STREQUAL regen_hash)
        list(APPEND mismatches "${name} (committed != regenerated)")
    endif()
endforeach()

if(NOT mismatches STREQUAL "")
    string(REPLACE ";" "\n  " pretty "${mismatches}")
    message(FATAL_ERROR
        "golden inputs are NOT reproducible byte-identical:\n  ${pretty}\n"
        "Re-run gen_golden_inputs into tests/golden/inputs/ and commit, or fix "
        "the synthesis so it is deterministic.")
endif()

message(STATUS "goldeninputs: all ${committed_wavs} regenerated byte-identical")
