#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# mwStime — Akai S-series timestretch emulation. Copyright (C) 2026 mattWoolly.
#
# bless_goldens.sh — the GATED blessing procedure (docs/design/testing-strategy.md
# §4 "Blessing procedure"; task plan/backlog/026-golden-harness.md). Wrapped by the
# `bless_goldens` CMake target. Re-renders every case in cases.json into
# tests/golden/blessed/ on the reference platform (macOS arm64) and writes
# tests/golden/blessed/MANIFEST.json (engine version hash, date, blesser, reason).
#
# HARD GATE: refuses to run unless BLESS_REASON is set to a non-empty string.
# Blessing is only allowed in a PR whose description quotes the reason and links an
# ADR or bug; the review agent must explicitly approve golden changes
# (testing-strategy.md §4 — golden churn without an audible/intentional change is a
# review-rejection criterion). MANIFEST.json is rewritten every bless (its date /
# blesser / reason fields change by design), so a same-commit re-bless changes only
# the MANIFEST, never the WAVs (the task verification command checks exactly this).
#
# Usage (normally via the CMake target, which fills in the paths):
#   BLESS_REASON="why" bless_goldens.sh <render-bin> <cases.json> <case-list> \
#                       <inputs-dir> <blessed-dir>
#
#   <case-list> : a text file, one "<id> <policy>" per line, generated by
#                 tests/golden/CMakeLists.txt from cases.json at configure time
#                 (so this script needs no JSON parser of its own).
#
# The engine version + hash are read from the render binary itself
# (mwstime-render --engine-version), so the renderer stays the single
# authoritative source of the version recorded in MANIFEST.json.

set -euo pipefail

if [ "$#" -ne 5 ]; then
    echo "usage: bless_goldens.sh <render-bin> <cases.json> <case-list> \
<inputs-dir> <blessed-dir>" >&2
    exit 2
fi

render_bin="$1"
cases_json="$2"
case_list="$3"
inputs_dir="$4"
blessed_dir="$5"

# Engine version + hash straight from the renderer (one line: "<ver> 0x<hash>").
read -r engine_version engine_hash < <("$render_bin" --engine-version)

# --- the gate ---------------------------------------------------------------
if [ -z "${BLESS_REASON:-}" ]; then
    echo "bless_goldens: REFUSED — BLESS_REASON is not set." >&2
    echo "  Blessing rewrites the committed golden renders. Set a justification:" >&2
    echo "    BLESS_REASON=\"<why; link an ADR/bug>\" cmake --build --preset default --target bless_goldens" >&2
    echo "  Policy: testing-strategy.md §4 — golden churn without an audible/" >&2
    echo "  intentional change is a review-rejection criterion." >&2
    exit 1
fi

if [ ! -f "$case_list" ]; then
    echo "bless_goldens: case list not found: $case_list" >&2
    exit 2
fi

mkdir -p "$blessed_dir"

echo "bless_goldens: re-rendering the golden corpus into $blessed_dir"
echo "  reason : $BLESS_REASON"
echo "  engine : $engine_version (hash $engine_hash)"

count=0
while read -r id _policy; do
    [ -z "$id" ] && continue
    case "$id" in \#*) continue ;; esac   # allow comment lines
    out="$blessed_dir/${id}.wav"
    "$render_bin" --case "$id" --cases "$cases_json" \
        --inputs-dir "$inputs_dir" --out "$out" > /dev/null
    count=$((count + 1))
done < "$case_list"

echo "bless_goldens: re-rendered $count cases"

# --- MANIFEST.json ----------------------------------------------------------
# Date is UTC ISO-8601 (stable format); blesser comes from the environment so a
# CI/agent bless is attributable. The reason is JSON-escaped minimally (the env
# var is operator-supplied, so we escape backslashes and double-quotes).
date_utc="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
blesser="${BLESS_BLESSER:-${USER:-unknown}}"
platform="$(uname -sm)"

json_escape() {
    # Escape backslash then double-quote; collapse newlines to spaces.
    printf '%s' "$1" | tr '\n' ' ' | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}
reason_escaped="$(json_escape "$BLESS_REASON")"
blesser_escaped="$(json_escape "$blesser")"
platform_escaped="$(json_escape "$platform")"

manifest="$blessed_dir/MANIFEST.json"
cat > "$manifest" <<EOF
{
  "engineVersion": "$engine_version",
  "engineVersionHash": "$engine_hash",
  "date": "$date_utc",
  "blesser": "$blesser_escaped",
  "platform": "$platform_escaped",
  "reason": "$reason_escaped",
  "caseCount": $count
}
EOF

echo "bless_goldens: wrote $manifest"
echo "bless_goldens: done"
